### ISSUE TITLE
Handling videos at higher res

### ISSUE THREAD

**Issue by siddhantjain** [hassony2/kinetics_i3d_pytorch#12]
Hello,

I was wondering if you have figured out how to use I3D for higher res videos without going out of memory. I am using I3D for video object segmentation (have modified the network to give a segmentation output) and finding it hard to run all frames at 480p resolution for even a single video. My batch size is one and the max number of frames I can process without filling up a 12GB GPU are 24 or so. If I resize the video down to 224x224 I can manage to run all 100 frames in the video, but I am losing a lot of information this way and my results are not as great.

While training I by-passed the problem by taking random 224x224 crops of the full res image. But for inference I can't use this trick and hence wondering how to solve this issue. Any ideas?

**Comment by hassony2** [comment]
Hi @siddhantjain,

Sorry for the late response, I have not worked with higher resolution videos.
However, several suggestions:
- I think the idea you had, e.g. downsampling is a good first step
- you can tweek the network to reduce the memory consumption 
    - for instance increasing the stride of the first convolution
    - or adding a convolution + pooling layer at the very beginning in the network
- at inference time you can try to use the `with torch.no_grad():` context which should reduce memory usage

Hope this helps !

Best,

Yana
