### ISSUE TITLE
Pretrained model on Kinetics

### ISSUE THREAD

**Issue by LiliMeng** [hassony2/kinetics_i3d_pytorch#15]
Hi,
Thanks a lot for providing the open-source I3D pytorch code! May I ask do you provide the pretrained model on Kinetics? 

Highly appreciate your time and help!

**Comment by hassony2** [comment]
Hi @LiliMeng,

The pretrained models (transfered from tensorflow) can be found in the repo directly [here](https://github.com/hassony2/kinetics_i3d_pytorch/blob/master/model/model_rgb.pth) (for the case of rgb in this case !).

All the best,

Yana
