### ISSUE TITLE
Fine-tune on HMDB51 or other datasets

### ISSUE THREAD

**Issue by LiliMeng** [hassony2/kinetics_i3d_pytorch#16]
Thanks a lot for providing the open-source code!

Could you please provide the code for fine-tuning on HMDB51 or some other datasets such as Moments in Time or UCF101?

Highly appreciate your time and help!

**Comment by hassony2** [comment]
Hi @LiliMeng,

Unfortunately I never finetuned on any of the datasets you mention, as I focus on first-person view.

All the best,

Yana
