### ISSUE TITLE
python i3d_tf_to_pt.py  --rgb

### ISSUE THREAD

**Issue by Zhuysheng** [hassony2/kinetics_i3d_pytorch#17]
Traceback (most recent call last):
  File "i3d_tf_to_pt.py", line 9, in <module>
    from src.i3dtf import InceptionI3d
  File "/home/zhuyisheng/kinetics_i3d_pytorch/src/i3dtf.py", line 32, in <module>
    class Unit3Dtf(snt.AbstractModule):
AttributeError: 'module' object has no attribute 'AbstractModule'

**Comment by hassony2** [comment]
Hi @Zhuysheng,

Can you try

```
pip uninstall sonnet
pip install dm-sonnet
```

and try again ?
Let me know how it goes !

Best,

Yana

**Comment by Zhuysheng** [comment]
@hassony2 thanks！
