### ISSUE TITLE
What is the source of slight drift in the weights?

### ISSUE THREAD

**Issue by yelantingfeng** [hassony2/kinetics_i3d_pytorch#18]
As you mentioned in readme, there is a slight drift in weights. I wonder what causes this drift. Thank you for your generous help in advance.

**Comment by hassony2** [comment]
Unfortunetaly, I do not know where this imprecision comes from. In my experiments, I could transfer 2D convolutions perfectly but only with a slight drift when I used 3D convolutions.

If you discover the answer to this riddle, let me know !
